[package]
name = "fastmerkle-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
crossbeam-channel = "0.5.13"
hex = "0.4.3"
rand = "0.8.5"
criterion = "0.5.1"